name: Update Recent Activity

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC

jobs:
  fetch_activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch recent activity
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIVITY_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/users/YOUR_USERNAME/events \
          > data.json

      - name: Commit and push updates
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update recent activity"
          git push
